# Development Environment Configuration
# This is a sample dev configuration - customize as needed

secrets:
  databricks_secret_scope: 'dev-keyvault'
  keyvault_url: 'https://dev-keyvault.vault.azure.net/'

general:
  dead_letter_queue:
    kafka: null
    topic: 'dev_dead_letter_queue'
  
  streaming:
    checkpoint_path: 'abfss://spark-streaming-checkpoint@devstorageaccount.dfs.core.windows.net'
    consumer_group_prefix: 'dev_'
    fail_on_missed_kafka_records: false
  
  schema_service:
    schema_service_basic_auth_password_vault_key: null
    schema_service_basic_auth_username: null
    schema_service_url: 'http://api.dev.example.com'
  
  kafka:
    main:
      host: 'dev-eventhubs.servicebus.windows.net'
      sas_key: null
      supports_compression: false
      use_oauth: true
  
  kafka_oauth:
    client_id: 'dev-client-id'
    client_secret_vault_key: 'dev-client-secret'
    token_url: 'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token'
